apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: podinfo-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /podinfo-dev
        backend:
          serviceName: podinfo-dev
          servicePort: http