apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo
  namespace: dev
  labels:
    k8s-app: podinfo
    app: podinfo
    release: prometheus-operator
spec:
  jobLabel: podinfo
  selector:
    matchLabels:
      app: podinfo
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
