apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgAZHpVzR6TGJ2olBHUO1goiJZs4robx8Y/1VYsNhqUvr1qTy6phKhoJtxjEl0kI2h9MHUkk+h/T4XZ/8dyBrKB7gapAnxQK3elfVB7P7621fSaWwTqky2fsRsTRifaYzQLSBlKdEoIRG+ybJya0uwOdb3vdSgRpUwoBSlw4/BF5jbXieW+uoit3GwWFG9Tki9Gde0rahDtxqlpH7YfaQK3eueFQurGFvweg5vfp4VTBDrP8Jk0jJA6y+u6IVbUZnDsw3hQUsqMS4vtsulhrLlqHpR66qyO2ukL5mupNvi7K08NLfbUyJ2Xve91HV2puhAQq1/Hlk7drXDYSKQRkynqdhz/XTBX1tfEVAhlMaAylDfOgnJFZGl9PQrbPKBhIYDe3AwYNOuhpkPEYx74eIqhGN8Ffo9DkgjbVKK8MSNLn726dNQdVzmfQYd/HWsa8hWgz0cL5n9EryNrYAYQ19leKCzMf5gvzl1f/JTUFR9YrylaC9VnUYvLyjifr7m9eFEw2MtFNzwabZJ01LQGMqhDA2AhAe1pF7W0MsXwphGnQdh4uCj9SEZoNgivg6o0LVothUlmce12NLtjYzRhO5QodtlluGo7+Qu0G2S6N6T0WSsd4z2lm8kR0m/HEWJkbruVV4M0jpBjbEgVEFA6/Gzk98uA66p6YwZSKHvTto9PDZdW8CTwc05sCinqQHTb2xE3DqrR52ND7Oe5VcVE=
    username: AgAOcBCKuSVUt73MWjvfNJJktQlRfiNzdI5ifC3SoO07MLjQhiobe56NsOzPcNOGd8x3H90DRSBenpPBYVDuL+1NRPJmeDJKalksVj/rBe1CHNI6HaFcNRpXldWIjEqbYr9f1m5+hfNM8jMyMlRjzRimMtPCrzEKg7zpnPho29W0uO1qQHj4vi4ezsNEyJpncW2bSf+Vjs2lKfAVvSyvYUoe/JApEySIDHHzsVhw35fizaNnppQm8Cv5H8da5SaeD3jA7/WoDH+Qt80XQEjdvmC15L8p5ljqYjmAbSDYqkqHmmqkF+gky9wC87e08uWhsFlX04kjBlZAPm4GZpEnYW6WcW/fsj4W3JYWFw4oUqgvlD//gsxRTzOhmGiXSTGgx572n8xw4VCd0XTIjUpgzMeoZkCPl6wLEUA1/KFhqCZNVKTcGmLZT+Yn00yDGMQQKDnHG2zaCMmFrO5EAaM5YZeq7q3/v5907oKjXlaFyrM5Ir0IiDlxfAjfa+jqmYTU5nI+6ymBv7Imhv461fm2I23EVPan+GarOfvyWjAZGgDh3ORZZjWN7Fr7Iw5/IEmGU2hBwxua8HvD83oh6gM5BWxiJqc2ILyAu3xyefQij48gbG/QkNSQ88KkaBvBP3IjpbcPBM3LDIRJ0z6Q+GqGY9gSI6f7Na+8WeS9DowmrWTdv++5uZt1wn51GKiCWjtZK2LBeoZffw==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
    type: Opaque

