apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-main
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yaml: AgA9xJV5iAPjks27JBh7s1YNyGpWObcXID6YqVSzGK8qjH2Ji52CyRX96kQFXuBwz6EfrXafAzGLZ9+X+V0733FcxBN7oczruGR4n0gOiX09m1t2FpuqUf/v3PA923AhXQE6JCPf3OF/PYizMYZjrMt3SQXk8Kp9i7Ilw8zadj664AxBnl10KLTbtzGjxO8jK3bgFnpP68GOdYjWaNMLpomJ0/ofCv/mU7OifHEi6V1qPCMqP6LCxL26NYzwY73YVH0/eiv1kwV6pev/DlWk1UH5kGNOLqgo8Ov/uMEO/KZ5LvaLbvvKLhcX9Ascw8nFTxsMgFdvXp+ruVzpimp9x8N5ukxrtvLLpG0CnGbG/BnzoYg9F33n+a1lKrMKIgszzp8tj5qWLSD2myz1umB2MiXZQuM23pS+yXNuV8eZ5huEx7nYWhgXWuhnduUrKIZmcJIPpPvRmZKdIBU0Veyxn8kKuPUkzrjBhrr25CG6eBC+TBA8IK4vHRSLNCbyAYPyMjWaH6MAUim9TIy6ofQTAvF+UYMDILSvIyxXggblnS4yT6CitulcNNVPCGgGMYIDJm93b1nJ7amGNnzrjb8/j7VVkay4OLfdwxwBOZS1AxWzgvn3wpfUsl7oaWO9o5IFBgMsV27joYiJqBB4b9N0MNOsMipes9SXYbQasBG/TVFHc8eDNmsWZpFguTghh+6wC4idhiJ/0vgjqTiWMh6zWOnwAy0cE9h6r5KEoMoyJKEshAkvSb/FTHJgGdvssV86MGm/eJgC3RaAOFyb2CQ2QTaS7J+OzqQad9ViD2JOsIPd0dHv1zAkFG4SWbgf1Y8X6UP596TI0UWkRiH0bFQKtAu/mCMOnLoi4E+IFT28ChQL6VNAP54/FL6LB0HKSvM7yzTMUr5NzszViVoo4sBURD+YMaabqx5zNb9rl+baSx4yu/lqZZfBgxLI5UUeKsqIT0nbSc6oT/UuD3tPcSvrFaI5fM/74YeRK58J3MYEt+T0VTAMVJY3UpDBlD3VelNIZmerheLpygJKuClLN7SYZaII/qZsgusAihOZXFgIR17pcsNVcWQAcWqD0pWCVf7DicFM9u3u4ojVhkdIIrKX/JApAbZQerBlUJhL0t2XsmZhEXlFZO4mqYWC8Nxi2XyFyKrJdktV5c/OrMdhNDEGPLYgEuDte+TchzR/Y240abM+EIQHs0INfCDk7tu5UunaS3xZhZyy3LVR84ll6SqGhdaQVMecVUG6QT6rgimcjo6TyLRuIgD9OdEqSrvlMeC1K1j06Q99Iy82PZJn5FSqPxSzLqVI2u/T9YAxYqA88cSZNc1PM+qauspLC7jyHatRQG4PzvwtmwTBPXrFoNGpSO/EFOd4/Is0OW7DHNs2kuizPlW2KeMn85rjrGfS738Q3O1SWTqp2YxSsBohhLG4DlZpDV6ed32DE1C++9WQI8HpLzXa5bNcy/PVSdn+RJ0UfdP9SpIkx4D1Tdn4dGGXmuiAyD3hMA722cLLOfONhjyxlOsWe9Dol+mMli3MDYfMI8J0/KJEAlfVo1YgqhfjUn8B8YpzbJVpRsKgepWhfhAAQKJC1v1GpaPGNbGNw953g7QTW1LkHW8qimxW8e+Ns1rP7swzjGuU19IuNs2B+UGUWedlSpYJoiyoM7vgGRxHGL0dWOCNg1Wt4TLLgBb4TS9WFmThwnD3w6lacSSB4MSgQ4dAl2oZnFakEg==
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-main
      namespace: monitoring
    type: Opaque
status: {}

