apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: success_rate
  namespace: stg
spec:
  provider:
    type: prometheus
    address: http://promethues-k8s.monitoring:9090
  query: |
    sum(
    rate(
    http_request_duration_seconds_count{
      service=~".*podinfo.*", 
      status=~"5.."}[1m])) 
      / 
      sum(
      rate(
      http_request_duration_seconds_count{
        service=~".*podinfo.*"}[1m]
        )
      )
