apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: podinfo-rc
  namespace: stg
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /podinfo-rc
        backend:
          serviceName: podinfo-rc
          servicePort: http