---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-rc
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: podinfo-rc
  chart:
    git: git@github.com:smcaine/gitops-demo.git
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: schaga/podinfo
      tag: stg-cqpvl75u
    replicaCount: 2
    hpa:
      enabled: true
      maxReplicas: 5
      cpu: 50
      memory: 256Mi
