apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flagger
  namespace: fluxcd
spec:
  releaseName: flagger
  chart:
    repository: https://flagger.app
    name: flagger
    version: 0.26.0
  values:
    meshProvider: nginx
    metricsServer: "http://prometheus-k8s.monitoring:9090"
    # slack:
    #   channel: gitops-demo
    # env:
    #   - name: SLACK_URL
    #     valueFrom:
    #       secretKeyRef:
    #         name: slackurl
    #         key: url